# Generated by Django 5.1 on 2024-08-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='imágen')),
                ('thumb', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='miniatura')),
            ],
            options={
                'verbose_name': 'imágen',
                'verbose_name_plural': 'imágenes',
            },
        ),
        migrations.CreateModel(
            name='QueryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(40, '4cm x 4cm'), (50, '5cm x 5cm'), (70, '7cm x 7cm')], verbose_name='tipo de impresion')),
                ('printed', models.BooleanField(default=False, verbose_name='lote impreso')),
            ],
            options={
                'verbose_name': 'lote de solicitudes',
                'verbose_name_plural': 'lotes de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='QueryImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagecontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.imagecontent')),
                ('querygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.querygroup')),
            ],
        ),
        migrations.AddField(
            model_name='querygroup',
            name='imagelist',
            field=models.ManyToManyField(blank=True, through='content.QueryImageRelation', to='content.imagecontent'),
        ),
    ]
